version: '3.8'

services:
  app:
    container_name: cinepik-catalog
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    env_file:
      - .env
    networks:
      - cinepik-network

networks:
  cinepik-network:
    name: cinepik-network
    external: true
