version: '3.8'

services:
  app:
    container_name: cinepik-catalog
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    networks:
      - cinepik-network

volumes:
  node_modules:


networks:
  cinepik-network:
    name: cinepik-network
    external: true
