version: '3.8'

services:
  app:
    container_name: cinepik-catalog
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    env_file:
      - .env
    networks:
      - cinepik-network
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:${LS_PORT}
        tag: cinepik-catalog

volumes:
  postgres_data:


networks:
  cinepik-network:
    name: cinepik-network
    external: true
