apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinepik-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinepik-catalog
  template:
    metadata:
      labels:
        app: cinepik-catalog
    spec:
      containers:
        - image: lzukanovic/cinepik-catalog:latest
          name: cinepik-catalog
          env:
            - name: PORT
              value: '3001'
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-credentials
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: KEYCLOAK_CLIENT_ID
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DATABASE_URL
          ports:
            - containerPort: 3001
              name: server
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: server
          #   initialDelaySeconds: 20
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: server
          #   initialDelaySeconds: 20
          #   periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cinepik-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: cinepik-catalog
